source 'https://rubygems.org'

gem 'activerecord'
gem 'database_cleaner'
gem 'fakeweb', '~> 1.3'
gem 'factory_bot'
gem 'httparty'
gem 'mysql2'
gem 'nokogiri'
gem 'redis'
gem 'resque'
#gem 'rest-firebase'
gem 'rspec'
gem 'twitter', '~> 5.6.0'
gem 'whenever', :require => false